apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
  # namespace: default
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: flink-kubernetes-operator-1.0.1
  annotations:
    "helm.sh/resource-policy": keep
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  # namespace: default
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: flink-kubernetes-operator-1.0.1
  annotations:
    "helm.sh/resource-policy": keep
roleRef:
  kind: Role
  name: flink
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: default
---
# Source: flink-kubernetes-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-operator
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: flink-kubernetes-operator-1.0.1
rules:
  - apiGroups:
      - flink-operator
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - deployments
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - flink.apache.org
    resources:
      - flinkdeployments
      - flinkdeployments/status
      - flinksessionjobs
      - flinksessionjobs/status
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "*"
---
# Source: flink-kubernetes-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-operator-cluster-role-binding
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: flink-kubernetes-operator-1.0.1
roleRef:
  kind: ClusterRole
  name: flink-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: default
