apiVersion: v1
kind: Service
metadata:
  name: flink-operator-webhook-service
  # namespace: default
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: flink-kubernetes-operator
---
# Source: flink-kubernetes-operator/templates/webhook.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flink-operator-serving-cert
  namespace: default
spec:
  dnsNames:
  - flink-operator-webhook-service.default.svc
  - flink-operator-webhook-service.default.svc.cluster.local
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: flink-operator-webhook-secret
        key: password
  issuerRef:
    kind: Issuer
    name: flink-operator-selfsigned-issuer
  commonName: FlinkDeployment Validator
  secretName: webhook-server-cert
---
# Source: flink-kubernetes-operator/templates/webhook.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: flink-operator-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: flink-operator-webhook-secret
  namespace: default
type: Opaque
data:
  password: cGFzc3dvcmQxMjM0
# Source: flink-kubernetes-operator/templates/webhook.yaml
# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#   annotations:
#     cert-manager.io/inject-ca-from: default/flink-operator-serving-cert
#   name: flink-operator-default-webhook-configuration
# webhooks:
# - name: flinkoperator.flink.apache.org
#   admissionReviewVersions: ["v1"]
#   clientConfig:
#     service:
#       name: flink-operator-webhook-service
#       namespace: default
#       path: /validate
#   failurePolicy: Fail
#   rules:
#   - apiGroups: ["*"]
#     apiVersions: ["*"]
#     scope: "Namespaced"
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - flinkdeployments
#     - flinksessionjobs
#   sideEffects: None
